/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_sammyne_helloworld_HelloWorld */

#ifndef _Included_com_github_sammyne_helloworld_HelloWorld
#define _Included_com_github_sammyne_helloworld_HelloWorld
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:      com_github_sammyne_helloworld_HelloWorld
 * Method:     increment
 * Signature:  (I)I
 */
JNIEXPORT jint JNICALL Java_com_github_sammyne_helloworld_HelloWorld_increment
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
